name = "BlanketCon '25"
author = "ModFest"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
unsup = "1.0.2"
unsup-experimental = "1.1-pre8"
unsup-stable = "1.0.2"

[options]
datapack-folder = "resources/datapack/required"
no-internal-hashes = true
